[package]
name = "xbyte-evm"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-sol-types.workspace = true
alloy-contract.workspace = true
alloy-provider.workspace = true
alloy-primitives.workspace = true
anyhow.workspace = true

[dev-dependencies]
tokio.workspace = true
