[package]
name = "xbyte_app"
version = "0.1.0"
edition = "2024"

[dependencies]
xbyte_api.workspace = true
anyhow.workspace = true
tokio.workspace = true
dotenv.workspace = true
tracing-subscriber.workspace = true
