name: CI - xByte Client

on:
  push:
    branches: [master]
    paths:
      - "xbyte-web/**"
      - ".github/workflows/ci-xbyte-client.yml"
  pull_request:
    branches: [master]
    paths:
      - "xbyte-web/**"
      - ".github/workflows/ci-xbyte-client.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: xbyte-web

env:
  NEXT_PUBLIC_XBYTE_URL: ${{ secrets.NEXT_PUBLIC_XBYTE_URL }}
  NEXT_PUBLIC_RPC_URL: ${{ secrets.NEXT_PUBLIC_RPC_URL }}
  NEXT_PUBLIC_CHAIN_ID: ${{ secrets.NEXT_PUBLIC_CHAIN_ID }}

jobs:
  fromat:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.4
          cache: true
          cache-dependency-path: xbyte-web/bun.lock
      - name: Run Format Check
        run: bunx oxfmt@latest -c .oxfmtrc.jsonc --check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.4
          cache: true
          cache-dependency-path: xbyte-web/bun.lock
      - name: Run Lint Check
        run: bunx oxlint@latest --deny-warnings
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 25.2.1
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.4
          cache: true
          cache-dependency-path: xbyte-web/bun.lock
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Build
        run: bun run build
